language:
  node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm i coveralls -g
  - npx jest test --coverage --coverageReporters=text-lcov | coveralls
  - npm test
  - npx codecov
